package com.yuchengtech.crm.dataauth.action;

import javax.servlet.http.HttpServletRequest;
import javax.sql.DataSource;

import org.apache.struts2.ServletActionContext;
import org.apache.struts2.convention.annotation.Action;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.security.core.context.SecurityContextHolder;

import com.opensymphony.xwork2.ActionContext;
import com.yuchengtech.bob.common.CommonAction;
import com.yuchengtech.bob.vo.AuthUser;
import com.yuchengtech.crm.dataauth.model.OcrmSysViewManagerComm;
import com.yuchengtech.crm.dataauth.service.MyCustViewService;

/**
 * @describtion: autogenerated by lhqheli's Tools
 * 
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-07-31 10:31:17
 */
@Action("/myCustView")
public class MyCustViewAction extends CommonAction{

    private static final long serialVersionUID = 1L;
    
    @Autowired
    @Qualifier("dsOracle")
    private DataSource ds;
    
    @Autowired
    private MyCustViewService myCustViewService;
    
    @Autowired
    public void init(){
        model = new OcrmSysViewManagerComm();
        setCommonService(myCustViewService);
    }
    
    public void prepare(){
        AuthUser auth = (AuthUser)SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        StringBuffer sb = new StringBuffer("SELECT t.* FROM OCRM_SYS_VIEW_MANAGER_COMM t WHERE 1=1 ");
        for(String key:this.getJson().keySet()){
            if(null!=this.getJson().get(key) && !"".equals(this.getJson().get(key))){
                if("ID".equals(key)){
                    sb.append(" AND t.ID = '"+this.getJson().get(key)+"'");
                }
            	if("NAME".equals(key)){
                    sb.append(" AND t.NAME LIKE '%"+this.getJson().get(key)+"%'");
                }
            }
        }
        SQL = sb.toString();
        datasource =ds;
    }
    
    /**
     * batch delete myCustView
     */
    public String batchDestroy(){
        ActionContext ctx = ActionContext.getContext();
        request =(HttpServletRequest) ctx.get(ServletActionContext.HTTP_REQUEST);
        String ids = request.getParameter("ids");
        myCustViewService.batchRemove(ids);
        return "success";
    }
}
