package com.yuchengtech.crm.dataauth.service;

import java.util.HashMap;
import java.util.Map;

import org.springframework.stereotype.Service;

import com.yuchengtech.bob.common.CommonService;
import com.yuchengtech.bob.common.JPABaseDAO;
import com.yuchengtech.crm.dataauth.model.OcrmSysViewManagerComm;

/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-07-31 10:31:17
 */
@Service
public class MyCustViewService extends CommonService {
    public MyCustViewService(){
        JPABaseDAO<OcrmSysViewManagerComm, Long> baseDao = new JPABaseDAO<OcrmSysViewManagerComm, Long>(OcrmSysViewManagerComm.class);
        super.setBaseDAO(baseDao);
    }
    
    /**
     * create or update myCustView
     */
    public Object save(Object obj) {
        OcrmSysViewManagerComm myCustView = (OcrmSysViewManagerComm)obj;
        return super.save(myCustView);
    }
    
    /**
     * bacth delete myCustView
     */
    public void batchRemove(String ids) {
        Map<String, Object> values = new HashMap<String, Object>();
        super.batchUpdateByName("DELETE FROM OcrmSysViewManagerComm t WHERE t.id IN("+ ids +")", values);
    }
}
