package com.yuchengtech.crm.system.ui.search.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
/**
 * @describtion: autogenerated by lhqheli's Tools
 *
 * @author : lhqheli (email: lhqheli@gmail.com)
 * @date : 2014-08-13 11:24:20
 */
@Entity
@Table(name="OCRM_F_SYS_USER_CFG")
public class OcrmFSysUserCfg implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
	@GeneratedValue(generator = "CommonSequnce", strategy = GenerationType.TABLE)
    @Column(name="ID")
    private Long id;

    @Column(name="USER_ID")
    private String userId;

    @Column(name="THEME_CSS")
    private String themeCss;

    @Column(name="BG_ICON")
    private String bgIcon;

    @Column(name="WORD_SIZE")
    private String wordSize;

    @Column(name="SPARE_ONE")
    private String spareOne;

    @Column(name="SPARE_TWO")
    private String spareTwo;


    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public String getUserId(){
        return this.userId;
    }

    public void setUserId(String userId){
        this.userId = userId;
    }

    public String getThemeCss(){
        return this.themeCss;
    }

    public void setThemeCss(String themeCss){
        this.themeCss = themeCss;
    }

    public String getBgIcon(){
        return this.bgIcon;
    }

    public void setBgIcon(String bgIcon){
        this.bgIcon = bgIcon;
    }

    public String getWordSize(){
        return this.wordSize;
    }

    public void setWordSize(String wordSize){
        this.wordSize = wordSize;
    }

    public String getSpareOne(){
        return this.spareOne;
    }

    public void setSpareOne(String spareOne){
        this.spareOne = spareOne;
    }

    public String getSpareTwo(){
        return this.spareTwo;
    }

    public void setSpareTwo(String spareTwo){
        this.spareTwo = spareTwo;
    }


}
